device: cuda

dataset:
  path: "data/2D/diffusion-reaction/2D_diff-react_NA_NA.h5"
  input_timesteps: [0, 1, 2, 3, 4]
  target_timestep: 100
  resolution: [64, 64]  # (x_res, y_res) or null to keep the original resolutionx
  from_sample: 980
  to_sample: 1000

architecture:
  from_checkpoint: .checkpoints/arafno2d/epoch5.pt
